
class WorkoutsList {
// Class responsible for showing workouts (To-do : turn it into API)
  static List allWorkoutsList = [
    {
      "workOutTitle": "Airdyne bike",
      "imagePath": "imgs/airdyne_bike.jpg",
      "timeLeftInHour": "18",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "The airdyne bike is a high-intensity cardio machine that can be used to perform a variety of workouts. To do an airdyne bike workout, simply set the resistance to a challenging level and pedal as fast as you can for a predetermined amount of time.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Deadlift",
      "imagePath": "imgs/deadlifts.jpg",
      "timeLeftInHour": "16",
      "movesNumber": "100",
      "setsNumber": "30",
      "durationInMinutes": "55",
      "rating": "5",
      "description": "The deadlift is a compound exercise that works the hamstrings, glutes, and back. To do a deadlift, stand with your feet shoulder-width apart and bend over at the waist, keeping your back straight. Grab a barbell or dumbbells with an overhand grip, and lift it up off the ground until it is in front of your thighs. Lower the weight back to the ground in a controlled manner.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "55,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "Handstand push-up",
      "imagePath": "imgs/handstand_push_ups_img.jpg",
      "timeLeftInHour": "7",
      "movesNumber": "50",
      "setsNumber": "0",
      "durationInMinutes": "32",
      "rating": "4",
      "description": "The handstand push-up is a challenging exercise that works the shoulders, triceps, and core. To do a handstand push-up, start in a handstand position with your hands shoulder-width apart. Lower your body down until your chest touches the ground, then push back up to the starting position.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "24,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "Kettlebell swing",
      "imagePath": "imgs/kettlebell_swing.jpg",
      "timeLeftInHour": "18",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "The kettlebell swing is a dynamic exercise that works the hips, hamstrings, and glutes. To do a kettlebell swing, stand with your feet shoulder-width apart and hold a kettlebell in front of you with both hands. Swing the kettlebell back between your legs, then explosively swing it up to chest height.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Olympic weightlifting",
      "imagePath": "imgs/olympic_weightlifting.jpg",
      "timeLeftInHour": "16",
      "movesNumber": "100",
      "setsNumber": "30",
      "durationInMinutes": "55",
      "rating": "5",
      "description": "Olympic weightlifting is a competitive sport that involves the snatch and the clean and jerk. The snatch is a lift in which the barbell is lifted from the ground to overhead in one motion. The clean and jerk is a lift in which the barbell is first lifted to the chest, then overhead.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "55,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "Sprints",
      "imagePath": "imgs/sprints.jpg",
      "timeLeftInHour": "7",
      "movesNumber": "50",
      "setsNumber": "0",
      "durationInMinutes": "32",
      "rating": "4",
      "description": "Sprints are a high-intensity cardio exercise that can be done on a treadmill, track, or other surface. To do sprints, run as fast as you can for a short distance, then rest for a short period of time. Repeat this for a predetermined number of intervals.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "24,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
    },
    {
      "workOutTitle": "Power yoga",
      "imagePath": "imgs/power_yoga.jpg",
      "timeLeftInHour": "19",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Power yoga is a vigorous style of yoga that combines traditional yoga poses with cardio and strength training exercises. It is a great way to get a full-body workout.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "Warrior Pose",
      "imagePath": "imgs/warrior_pose_img.jpg",
      "timeLeftInHour": "18",
      "movesNumber": "24",
      "setsNumber": "12",
      "durationInMinutes": "20",
      "rating": "4",
      "description": "The warrior pose is a standing pose that strengthens the legs and core. It is also a good pose for improving balance and focus.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "8,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "Downward Pose",
      "imagePath": "imgs/Downward_facing_dog_pose.jpg",
      "timeLeftInHour": "23",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "3",
      "description": "The downward-facing dog pose is a backbend that stretches the spine and shoulders. It is also a good pose for improving circulation.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Corpse Pose",
      "imagePath": "imgs/corpse_pose.jpg",
      "timeLeftInHour": "19",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "The corpse pose is a resting pose that is calming and relaxing. It is also a good pose for allowing the body to integrate the benefits of the other poses.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Bridge Pose",
      "imagePath": "imgs/bridge-Pose.jpg",
      "timeLeftInHour": "18",
      "movesNumber": "24",
      "setsNumber": "12",
      "durationInMinutes": "20",
      "rating": "4",
      "description": "The bridge pose is a hip opener that strengthens the back and legs. It is also a good pose for improving posture.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "8,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
    },
    {
      "workOutTitle": "Triangle Pose",
      "imagePath": "imgs/warrior_pose_img.jpg",
      "timeLeftInHour": "23",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "3",
      "description": "The triangle pose is a side bend that stretches the sides of the body. It is also a good pose for improving balance and coordination.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "Push-ups",
      "imagePath": "imgs/push_ups_img.jpg",
      "timeLeftInHour": "10",
      "movesNumber": "40",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "5",
      "description": "This is a classic push exercise that works the chest, shoulders, and triceps. To do a push-up, start in a plank position with your hands shoulder-width apart and your body in a straight line from your head to your heels. Lower your body until your chest touches the ground, then push back up to the starting position.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "Bench press",
      "imagePath": "imgs/bench_press_img.jpg",
      "timeLeftInHour": "22",
      "movesNumber": "40",
      "setsNumber": "20",
      "durationInMinutes": "30",
      "rating": "5",
      "description": "This is another great push exercise that works the chest and triceps. To do a bench press, lie on a bench with your feet flat on the ground and your knees bent. Hold a barbell or dumbbells in your hands, palms facing up, with your arms extended straight up. Lower the weights to your chest, then press them back up to the starting position.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "30,00",
      "hasFreeTrial": "true",
      "isDiscounted": "true",
      "dailyFreeWorkout": "true",
    },
    {
      "workOutTitle": "Overhead press",
      "imagePath": "imgs/shoulder_Press_img.jpg",
      "timeLeftInHour": "23",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "3",
      "description": "This exercise works the shoulders and triceps. To do an overhead press, stand with your feet shoulder-width apart and hold a barbell or dumbbells in your hands, palms facing forward, at shoulder height. Press the weights overhead until your arms are straight, then lower them back to the starting position.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "Deadlift",
      "imagePath": "imgs/weightlifting_img.jpg",
      "timeLeftInHour": "10",
      "movesNumber": "40",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "5",
      "description": "This is a compound exercise that works the hamstrings, glutes, and back. To do a deadlift, stand with your feet shoulder-width apart and bend over at the waist, keeping your back straight. Grab a barbell or dumbbells with an overhand grip, and lift it up off the ground until it is in front of your thighs. Lower the weight back to the ground in a controlled manner.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "Pull-up",
      "imagePath": "imgs/pull_ups.jpg",
      "timeLeftInHour": "22",
      "movesNumber": "40",
      "setsNumber": "20",
      "durationInMinutes": "30",
      "rating": "5",
      "description": "This is a pull exercise that works the back and biceps. To do a pull-up, grab a pull-up bar with an overhand grip, and hang with your arms fully extended. Pull yourself up until your chin is over the bar, then lower yourself back down.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "30,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
    },
    {
      "workOutTitle": "Running",
      "imagePath": "imgs/running_img.jpg",
      "timeLeftInHour": "11",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Running is a great way to get your heart rate up and improve your cardiovascular health. It can be done indoors or outdoors, and it is a relatively low-impact exercise, making it a good option for people of all fitness levels.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "15,00",
      "hasFreeTrial": "false",
      "isWorkoutOfDay": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Cycling",
      "imagePath": "imgs/cycling_img.jpg",
      "timeLeftInHour": "9",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "1",
      "description": "Cycling is a great way to get some fresh air and enjoy the outdoors. It is also a low-impact exercise that can be done at a variety of intensities.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "Rowing",
      "imagePath": "imgs/rowing_img.jpg",
      "timeLeftInHour": "11",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "2",
      "description": "Rowing is a great full-body workout that works the arms, legs, and core. It is also a low-impact exercise that can be done indoors or outdoors.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "Jumping rope",
      "imagePath": "imgs/jumping_rope_img.jpg",
      "timeLeftInHour": "11",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Squat jumps are a great way to work your legs and glutes. To do a squat jump, start in a squat position. Jump up into the air and extend your legs as you jump. Land softly in the squat position",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "15,00",
      "hasFreeTrial": "false",
      "isWorkoutOfDay": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Squat jumps",
      "imagePath": "imgs/squat_jumps_img.jpg",
      "timeLeftInHour": "9",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "1",
      "description": "Squat jumps are a great way to work your legs and glutes. To do a squat jump, start in a squat position. Jump up into the air and extend your legs as you jump. Land softly in the squat position",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "HIIT",
      "imagePath": "imgs/hiit_img.jpg",
      "timeLeftInHour": "11",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "2",
      "description": "HIIT stands for high-intensity interval training. It is a type of cardio workout that involves alternating between short bursts of high-intensity exercise and periods of rest or low-intensity exercise. HIIT workouts are very effective for burning calories and improving cardiovascular health.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
    },
    {
      "workOutTitle": "Functional training",
      "imagePath": "imgs/functional_training_img.jpg",
      "timeLeftInHour": "23",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "3",
      "description": "Functional training exercises are designed to improve your ability to perform everyday activities. These exercises often involve compound movements that work multiple muscle groups at the same time.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
  ];

  static List cardioList = [
    {
      "workOutTitle": "Running",
      "imagePath": "imgs/running_img.jpg",
      "timeLeftInHour": "11",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Running is a great way to get your heart rate up and improve your cardiovascular health. It can be done indoors or outdoors, and it is a relatively low-impact exercise, making it a good option for people of all fitness levels.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "15,00",
      "hasFreeTrial": "false",
      "isWorkoutOfDay": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Cycling",
      "imagePath": "imgs/cycling_img.jpg",
      "timeLeftInHour": "9",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "1",
      "description": "Cycling is a great way to get some fresh air and enjoy the outdoors. It is also a low-impact exercise that can be done at a variety of intensities.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "Rowing",
      "imagePath": "imgs/rowing_img.jpg",
      "timeLeftInHour": "11",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "2",
      "description": "Rowing is a great full-body workout that works the arms, legs, and core. It is also a low-impact exercise that can be done indoors or outdoors.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "Jumping rope",
      "imagePath": "imgs/jumping_rope_img.jpg",
      "timeLeftInHour": "11",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Squat jumps are a great way to work your legs and glutes. To do a squat jump, start in a squat position. Jump up into the air and extend your legs as you jump. Land softly in the squat position",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "15,00",
      "hasFreeTrial": "false",
      "isWorkoutOfDay": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Squat jumps",
      "imagePath": "imgs/squat_jumps_img.jpg",
      "timeLeftInHour": "9",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "1",
      "description": "Squat jumps are a great way to work your legs and glutes. To do a squat jump, start in a squat position. Jump up into the air and extend your legs as you jump. Land softly in the squat position",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "HIIT",
      "imagePath": "imgs/hiit_img.jpg",
      "timeLeftInHour": "11",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "2",
      "description": "HIIT stands for high-intensity interval training. It is a type of cardio workout that involves alternating between short bursts of high-intensity exercise and periods of rest or low-intensity exercise. HIIT workouts are very effective for burning calories and improving cardiovascular health.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
    },
  ];

  static List strengthTraningList = [
    {
      "workOutTitle": "Push-ups",
      "imagePath": "imgs/push_ups_img.jpg",
      "timeLeftInHour": "10",
      "movesNumber": "40",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "5",
      "description": "This is a classic push exercise that works the chest, shoulders, and triceps. To do a push-up, start in a plank position with your hands shoulder-width apart and your body in a straight line from your head to your heels. Lower your body until your chest touches the ground, then push back up to the starting position.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "Bench press",
      "imagePath": "imgs/bench_press_img.jpg",
      "timeLeftInHour": "22",
      "movesNumber": "40",
      "setsNumber": "20",
      "durationInMinutes": "30",
      "rating": "5",
      "description": "This is another great push exercise that works the chest and triceps. To do a bench press, lie on a bench with your feet flat on the ground and your knees bent. Hold a barbell or dumbbells in your hands, palms facing up, with your arms extended straight up. Lower the weights to your chest, then press them back up to the starting position.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "30,00",
      "hasFreeTrial": "true",
      "isDiscounted": "true",
      "dailyFreeWorkout": "true",
    },
    {
      "workOutTitle": "Overhead press",
      "imagePath": "imgs/shoulder_Press_img.jpg",
      "timeLeftInHour": "23",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "3",
      "description": "This exercise works the shoulders and triceps. To do an overhead press, stand with your feet shoulder-width apart and hold a barbell or dumbbells in your hands, palms facing forward, at shoulder height. Press the weights overhead until your arms are straight, then lower them back to the starting position.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "Deadlift",
      "imagePath": "imgs/weightlifting_img.jpg",
      "timeLeftInHour": "10",
      "movesNumber": "40",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "5",
      "description": "This is a compound exercise that works the hamstrings, glutes, and back. To do a deadlift, stand with your feet shoulder-width apart and bend over at the waist, keeping your back straight. Grab a barbell or dumbbells with an overhand grip, and lift it up off the ground until it is in front of your thighs. Lower the weight back to the ground in a controlled manner.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "Pull-up",
      "imagePath": "imgs/pull_ups.jpg",
      "timeLeftInHour": "22",
      "movesNumber": "40",
      "setsNumber": "20",
      "durationInMinutes": "30",
      "rating": "5",
      "description": "This is a pull exercise that works the back and biceps. To do a pull-up, grab a pull-up bar with an overhand grip, and hang with your arms fully extended. Pull yourself up until your chin is over the bar, then lower yourself back down.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "30,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
    },
    {
      "workOutTitle": "Functional training",
      "imagePath": "imgs/functional_training_img.jpg",
      "timeLeftInHour": "23",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "3",
      "description": "Functional training exercises are designed to improve your ability to perform everyday activities. These exercises often involve compound movements that work multiple muscle groups at the same time.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
  ];

  static List yogaList = [
    {
      "workOutTitle": "Power yoga",
      "imagePath": "imgs/power_yoga.jpg",
      "timeLeftInHour": "19",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Power yoga is a vigorous style of yoga that combines traditional yoga poses with cardio and strength training exercises. It is a great way to get a full-body workout.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "Warrior Pose",
      "imagePath": "imgs/warrior_pose_img.jpg",
      "timeLeftInHour": "18",
      "movesNumber": "24",
      "setsNumber": "12",
      "durationInMinutes": "20",
      "rating": "4",
      "description": "The warrior pose is a standing pose that strengthens the legs and core. It is also a good pose for improving balance and focus.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "8,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "Downward Pose",
      "imagePath": "imgs/Downward_facing_dog_pose.jpg",
      "timeLeftInHour": "23",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "3",
      "description": "The downward-facing dog pose is a backbend that stretches the spine and shoulders. It is also a good pose for improving circulation.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Corpse Pose",
      "imagePath": "imgs/corpse_pose.jpg",
      "timeLeftInHour": "19",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "The corpse pose is a resting pose that is calming and relaxing. It is also a good pose for allowing the body to integrate the benefits of the other poses.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Bridge Pose",
      "imagePath": "imgs/bridge-Pose.jpg",
      "timeLeftInHour": "18",
      "movesNumber": "24",
      "setsNumber": "12",
      "durationInMinutes": "20",
      "rating": "4",
      "description": "The bridge pose is a hip opener that strengthens the back and legs. It is also a good pose for improving posture.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "8,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
    },
    {
      "workOutTitle": "Triangle Pose",
      "imagePath": "imgs/warrior_pose_img.jpg",
      "timeLeftInHour": "23",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "3",
      "description": "The triangle pose is a side bend that stretches the sides of the body. It is also a good pose for improving balance and coordination.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
  ];

  static List crossFit = [
    {
      "workOutTitle": "Airdyne bike",
      "imagePath": "imgs/airdyne_bike.jpg",
      "timeLeftInHour": "18",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "The airdyne bike is a high-intensity cardio machine that can be used to perform a variety of workouts. To do an airdyne bike workout, simply set the resistance to a challenging level and pedal as fast as you can for a predetermined amount of time.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Deadlift",
      "imagePath": "imgs/deadlifts.jpg",
      "timeLeftInHour": "16",
      "movesNumber": "100",
      "setsNumber": "30",
      "durationInMinutes": "55",
      "rating": "5",
      "description": "The deadlift is a compound exercise that works the hamstrings, glutes, and back. To do a deadlift, stand with your feet shoulder-width apart and bend over at the waist, keeping your back straight. Grab a barbell or dumbbells with an overhand grip, and lift it up off the ground until it is in front of your thighs. Lower the weight back to the ground in a controlled manner.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "55,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "Handstand push-up",
      "imagePath": "imgs/handstand_push_ups_img.jpg",
      "timeLeftInHour": "7",
      "movesNumber": "50",
      "setsNumber": "0",
      "durationInMinutes": "32",
      "rating": "4",
      "description": "The handstand push-up is a challenging exercise that works the shoulders, triceps, and core. To do a handstand push-up, start in a handstand position with your hands shoulder-width apart. Lower your body down until your chest touches the ground, then push back up to the starting position.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "24,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "Kettlebell swing",
      "imagePath": "imgs/kettlebell_swing.jpg",
      "timeLeftInHour": "18",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "The kettlebell swing is a dynamic exercise that works the hips, hamstrings, and glutes. To do a kettlebell swing, stand with your feet shoulder-width apart and hold a kettlebell in front of you with both hands. Swing the kettlebell back between your legs, then explosively swing it up to chest height.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Olympic weightlifting",
      "imagePath": "imgs/olympic_weightlifting.jpg",
      "timeLeftInHour": "16",
      "movesNumber": "100",
      "setsNumber": "30",
      "durationInMinutes": "55",
      "rating": "5",
      "description": "Olympic weightlifting is a competitive sport that involves the snatch and the clean and jerk. The snatch is a lift in which the barbell is lifted from the ground to overhead in one motion. The clean and jerk is a lift in which the barbell is first lifted to the chest, then overhead.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "55,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "Sprints",
      "imagePath": "imgs/sprints.jpg",
      "timeLeftInHour": "7",
      "movesNumber": "50",
      "setsNumber": "0",
      "durationInMinutes": "32",
      "rating": "4",
      "description": "Sprints are a high-intensity cardio exercise that can be done on a treadmill, track, or other surface. To do sprints, run as fast as you can for a short distance, then rest for a short period of time. Repeat this for a predetermined number of intervals.",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "24,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
    },
  ];
}
